name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, "${{ matrix.arch }}" ]

    strategy:
      matrix: 
        arch: [x86_64, aarch64]
      fail-fast: false

    steps:

    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag registry.nubificus.co.uk/ananos/solo5-faas:${{ matrix.arch }}
        docker push registry.nubificus.co.uk/ananos/solo5-faas:${{ matrix.arch }}

    - uses: docker/login-action@v1
       with:
          username: ${{ secrets.NBFC_USERNAME }}
          password: ${{ secrets.NBFC_PASSWORD }}
      run: |
        docker push registry.nubificus.co.uk/ananos/solo5-faas:${{ matrix.arch }}



  create_manifest:
    runs-on: [self-hosted]
    needs: build

    steps:
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.NBFC_USERNAME }}
          password: ${{ secrets.NBFC_PASSWORD }}

      - name: Create manifest
        run: |
            docker manifest create registry.nubificus.co.uk/ananos/solo5-faas:generic \
            --amend registry.nubificus.co.uk/ananos/solo5-faas:aarch64
            --amend registry.nubificus.co.uk/ananos/solo5-faas:x86_64
            docker manifest push registry.nubificus.co.uk/ananos/solo5-faas:generic
